language: java
jdk:
  - oraclejdk8

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "j8xwxkXgK3aqukyw15uuBZqOOkRiHLu/Hm7jHuyFLy6Rsekzy8juB1LnWiRXFTH9Bz9SB5Rgbh6+Bg/ceyAqgZU2nIeX5olUrEHFGN4BA29C0gkNoClGmCGqDuK4ytuanyNIc41gcY1SaT2lrnQ7d/E8pWKYl+2t36iT6tEyB8oelQUCIzIlf/yKNUZhrue9fVd+t+6R3AOjpHreHQwwKSYHJVd8NzZdgsY04FA8RYe158xgjS5KirqWwCB1e07HysWO/iS+cYHUBkSd8La87lrgkb6RC0v4EMMsWJfW9Fr7paB+v75XfocrU7+3DFGBI6lVhIWDoKZ0PNAI7WclmlD2MFTDNbLd8J8NWXhzqwIRJ8jm+db0riIJ/CP7CNcuoG0hdvY+GupdZ44Yq/0/Nmy7CZXlWnMI1YLz5jgA87muYY2l1fGXfUQ7BsdJKWepK24wSMgbhMHlwFTPF4nUfHfcw3cqkYWm+CGR971TRBinZTHzPpvF8kXVTjZUTeTceOgx6h8kygH9Vg9XMpd0JeZ/qN7LrZBgAVCeR6Mw1d1MXYq9rvOuLVcsEuFKeN6NYIXp+n9WDSNaaQvEPY4uoutV71KlfvSto77LGTt6z0sNjjlpXxEBnXjC3syBr4N253KYX4mtnZOy3lfXZqQxnQbyuGL1LzxhZtf68GnTVNs="
    - CODACY_PROJECT_TOKEN=24f7bf62b3fa4328aa3b9bf32c07b0d9

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 2>./openssl-connect.stderr | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

script:
  - if [[ ${COVERITY_SCAN_BRANCH} == 1 ]];
    then
        echo "Don't build on coverty_scan branch.";
        exit 0;
    fi
  - "./gradlew build"
  - "./gradlew dependencyCheckAnalyze || echo 'dependencyCheckAnalyze failed'"
  - "./gradlew sendCoverageToCodacy || echo sendCoverageToCodacy failed"

after_success:
  - "bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'"

addons:
  coverity_scan:
    project:
      name: "hmcts/ccd-data-store-api"
      description: "CCD Data Store API"
    notification_email: Dwayne.Bailey@HMCTS.net
    build_command: ./gradlew build
    branch_pattern: coverity_scan
